"""cisreport command line. Exit codes: 0 ok, 1 gate failed, 2 error."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path

from cisreport.compare import compare
from cisreport.config import ConfigError, check_consistency, load_controls, load_exceptions, load_policy
from cisreport.gate import failures
from cisreport.recap import RecapError, parse_recap
from cisreport.report import md, render_html, render_markdown, results_json
from cisreport.xccdf import ScanError, parse_results


def _report(args: argparse.Namespace) -> None:
    policy = load_policy(args.policy)
    controls, exceptions = load_controls(args.controls), load_exceptions(args.group_vars)
    before = parse_results(args.before.read_bytes(), policy.profile)
    after = parse_results(args.after.read_bytes(), policy.profile)
    check_consistency(controls, exceptions, set(after))
    recaps = parse_recap(args.second_run.read_text(encoding="utf-8", errors="replace"))
    comparison = compare(before, after, controls, exceptions)
    meta = dict(pair.split("=", 1) for pair in args.meta) | {"ssg": policy.ssg_version}
    out = args.out_dir
    out.mkdir(parents=True, exist_ok=True)
    call = (comparison, after, exceptions, recaps, policy, meta)
    (out / "results.json").write_text(results_json(*call), encoding="utf-8")
    (out / "summary.md").write_text(render_markdown(*call), encoding="utf-8")
    (out / "report.html").write_text(render_html(*call), encoding="utf-8")


def _controls_md(args: argparse.Namespace) -> None:
    lines = [
        "# Controls",
        "",
        "Generated by `cisreport controls-md` from `policy/controls.yml` and `inventory/group_vars/all.yml` (`cis_exceptions`).",
        "",
        "| CIS | Title | Role | SSG rules |",
        "|---|---|---|---|",
    ]
    for c in load_controls(args.controls):
        lines.append(f"| {md(c.cis)} | {md(c.title)} | {md(c.role)} | {md(', '.join(c.rules))} |")
    lines += ["", "## Documented exceptions", "", "| CIS | SSG rules | Reason | Owner |", "|---|---|---|---|"]
    for e in load_exceptions(args.group_vars):
        lines.append(f"| {md(e.cis)} | {md(', '.join(e.rules))} | {md(e.reason)} | {md(e.owner_role)} |")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="cisreport")
    sub = p.add_subparsers(dest="command", required=True)
    s = sub.add_parser("report")
    for name in ("--policy", "--controls", "--group-vars", "--before", "--after", "--second-run", "--out-dir"):
        s.add_argument(name, type=Path, required=True)
    s.add_argument("--meta", nargs="*", default=[])
    s = sub.add_parser("gate")
    s.add_argument("--results", type=Path, required=True)
    s = sub.add_parser("controls-md")
    for name in ("--controls", "--group-vars", "--out"):
        s.add_argument(name, type=Path, required=True)
    return p


def main(argv: Sequence[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        if args.command == "report":
            _report(args)
        elif args.command == "controls-md":
            _controls_md(args)
        else:
            problems = failures(json.loads(args.results.read_text(encoding="utf-8")))
            for problem in problems:
                print(f"gate: {problem}")
            if problems:
                return 1
            print("gate passed")
    except (ConfigError, ScanError, RecapError, OSError, ValueError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
