- name: Verify cis_services
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Read /etc/cron.allow
      ansible.builtin.slurp:
        src: /etc/cron.allow
      register: cis_check_0
    - name: /etc/cron.allow contains the expected setting
      ansible.builtin.assert:
        that:
          - >-
            'root' in (cis_check_0.content | b64decode)
    - name: Read /etc/at.allow
      ansible.builtin.slurp:
        src: /etc/at.allow
      register: cis_check_1
    - name: /etc/at.allow contains the expected setting
      ansible.builtin.assert:
        that:
          - >-
            'root' in (cis_check_1.content | b64decode)
