- name: Verify cis_logging
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Read /etc/systemd/journald.conf.d/60-cis.conf
      ansible.builtin.slurp:
        src: /etc/systemd/journald.conf.d/60-cis.conf
      register: cis_logging_check_0
    - name: /etc/systemd/journald.conf.d/60-cis.conf contains the expected setting
      ansible.builtin.assert:
        that:
          - >-
            'ForwardToSyslog=yes' in (cis_logging_check_0.content | b64decode)
